add self-update

diff --git a/mailer b/mailer
--- a/mailer
+++ b/mailer
@@ -2,20 +2,90 @@
 set -u
 set -e
 
+ML_VERSION="1.0"
+ML_GIT_REPO="https://github.com/lukasdanckwerth/bash-mailer.git"
+ML_GIT_TEMPLATE_URL="https://raw.githubusercontent.com/lukasdanckwerth/bash-mailer/main/mail.html2"
+ML_TEMPLATE="/etc/mailer/mail.html"
+ML_CONFIG="/etc/mailer/mailer.conf"
+ML_VERSION="/etc/mailer/mailer.version"
 MS_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
-MS_HTML_FILE=
+
+emph() {
+  echo "\033[1m${*}\033[0m"
+}
 
 # prints the help message
 print_usage() {
   echo -e "
 usage: mailer [<command>] [--help]
-  \033[1m --to,-t l\033[0m    Set the receiver
-  \033[1m --help, -h\033[0m   Print this help text and exit
+
+   $(emph "--from") mail           Set the sender.
+   $(emph "--to") mail             Set the receiver.
+   $(emph "--subject") subject     Set the subject of the mail.
+   $(emph "--headline") headline   Set the headline inside the mail.
+   $(emph "--footer") footer       Set the footer inside the mail.
+
+   $(emph "--file") filepath       Set the content of mail from file.
+   $(emph "--text") text           Set the content of mail.
+
+   $(emph "--help, -h")            Print this help text and exit
 "
+}
+
+random_string() {
+  echo $RANDOM | md5sum | head -c 32
 }
 
 temp_file() {
   mkdir -p "tmp/mailer/" && echo "/tmp/mailer/$(date +%s-%N).html"
+}
+
+die() {
+  echo -e "${*}" && exit 0
+}
+
+get_remote_version() {
+  git ls-remote "${ML_GIT_REPO}" HEAD | awk '{ print $1}'
+}
+
+print_version() {
+  die "$(ML_VERSION)"
+}
+
+download_mail_template() {
+  [[ -f "${ML_TEMPLATE}" ]] && die "template $(emph "${ML_TEMPLATE}") already existing"
+  [[ "$(whoami)" == "root" ]] || die "$(emph "update-template") must be run as root"
+  [[ "$(which curl)" == "" ]] && die "$(emph "curl") not found"
+  DL_TMP_TARGET="/tmp/mailer-$(random_string)"
+  curl "${ML_GIT_TEMPLATE_URL}" --out "${DL_TMP_TARGET}" --silent
+  [[ -f "${DL_TMP_TARGET}" ]] || die "can't download template"
+  cp -nf "${DL_TMP_TARGET}" "${ML_TEMPLATE}"
+  rm -rf "${DL_TMP_TARGET}"
+  [[ -f "${ML_TEMPLATE}" ]] || die "can't create template at: ${ML_TEMPLATE}"
+}
+
+update_mailer() {
+  [[ "$(whoami)" == "root" ]] || die "$(emph "update") must be run as root"
+  [[ "$(which git)" == "" ]] && die "$(emph "git") not found"
+  [[ "$(get_remote_version)" == "$(cat "${ML_VERSION}")" ]] && die "already up to date"
+  UP_TMP_TARGET="/tmp/mailer-$(random_string)"
+  git clone --quiet "${ML_GIT_REPO}" "${UP_TMP_TARGET}"
+  pushd "${UP_TMP_TARGET}" >/dev/null
+  echo $(git rev-parse HEAD) > "${ML_VERSION}"
+  make install
+  popd >/dev/null
+  rm -rf "${UP_TMP_TARGET}"
+  cat "${ML_VERSION}"
+}
+
+update_mail_template() {
+  download_mail_template
+}
+
+guard_template_existence() {
+  echo "guard_template_existence"
+  [[ -f "${ML_TEMPLATE}}" ]] && return
+  echo "not existing"
 }
 
 MAIL_FROM=""
@@ -27,8 +97,7 @@ MAIL_FOOTER=""
 MAIL_CONTENT=""
 MAIL_CONTENT_FILE=""
 
-MS_CONFIG="/etc/mailer/mailer.conf"
-[[ -f "${MS_CONFIG}" ]] && source "${MS_CONFIG}"
+[[ -f "${ML_CONFIG}" ]] && source "${ML_CONFIG}"
 
 MS_MAIL_TEMPLATE="/etc/mailer/mail.html"
 [[ -f "${MS_MAIL_TEMPLATE}" ]] || (echo "Missing file ${MS_MAIL_TEMPLATE}" && exit 0)
@@ -37,10 +106,6 @@ while (($# > 0)); do
   opt="${1}"
   shift
   case $opt in
-  --help | -h)
-    print_usage
-    exit 0
-    ;;
   --to | -t)
     MAIL_TO="${1}"
     shift
@@ -65,6 +130,22 @@ while (($# > 0)); do
     MAIL_CONTENT="${1}"
     shift
     ;;
+  --help | -h)
+    print_usage
+    exit 0
+    ;;
+  update | u)
+    update_mailer
+    exit 0
+    ;;
+  "update-templates" | ut)
+    update_mail_template
+    exit 0
+    ;;
+  version)
+    echo "get_remote_version: $(get_remote_version)"
+    exit 0
+    ;;
   *)
     die "Unknown command: '${opt}'.  Pass '--help' for a list of commands."
     ;;
@@ -73,7 +154,7 @@ done
 
 MS_TEMP_MAIL_HTML_FILE="/tmp/mailer-$(date +%s-%N).html"
 
-cat ${MS_MAIL_TEMPLATE} >> "${MS_TEMP_MAIL_HTML_FILE}"
+cat ${MS_MAIL_TEMPLATE} >>"${MS_TEMP_MAIL_HTML_FILE}"
 
 # cat "${MS_SCRIPT_DIR}/templates/startup.html" >>"${MS_TEMP_MAIL_CONTENT_HTML_FILE}"
 # sed -i "s/__DATE__/$(date '+%d.%m.%Y %T')/g" "${MS_TEMP_MAIL_CONTENT_HTML_FILE}"
@@ -96,7 +177,7 @@ elif [[ ! "${MAIL_CONTENT_FILE}" == "" ]]; then
   TMP_MAIL_CONTENT=$(cat "$MAIL_CONTENT_FILE")
   TMP_MAIL_CONTENT=$(echo "${TMP_MAIL_CONTENT//$'\n'/<br />}")
   TMP_FILE="/tmp/mailer-2-$(date +%s-%N).html"
-  echo "${TMP_MAIL_CONTENT}" > "${TMP_FILE}"
+  echo "${TMP_MAIL_CONTENT}" >"${TMP_FILE}"
   sed -i -e "/__CONTENT__/{r $TMP_FILE" -e "d}" "${MS_TEMP_MAIL_HTML_FILE}"
   rm -rf "${TMP_FILE}"
 fi
